openapi: 3.0.3
info:
  title: Tet Task Management API
  version: 1.0.0

servers:
  - url: /v1

paths:
  # Auth
  /auth/register:
    $ref: "./auth.yaml#/auth-register"
  /auth/login:
    $ref: "./auth.yaml#/auth-login"
  /auth/logout:
    $ref: "./auth.yaml#/auth-logout"
  /auth/profile:
    $ref: "./auth.yaml#/auth-profile"
  /auth/refresh-token:
    $ref: "./auth.yaml#/auth-refresh-token"

  # Task Category
  /task-categories:
    $ref: "./task.yaml#/task-categories"
  /task-categories/{categoryId}:
    $ref: "./task.yaml#/task-categories-id"

  # Tasks
  /tasks:
    $ref: "./task.yaml#/tasks"
  /tasks/{taskId}:
    $ref: "./task.yaml#/tasks-id"

  # Shopping Items
  /shopping-items:
    $ref: "./shopping.yaml#/shopping-items"
  /shopping-items/{itemId}:
    $ref: "./shopping.yaml#/shopping-items-id"

  # Budget
  /budgets:
    $ref: "./budget.yaml#/budgets"
  /budgets/{budgetId}:
    $ref: "./budget.yaml#/budgets-id"
  /users/total-budget:
    $ref: "./user.yaml#/total-budget"

components:
  schemas:
  # Auth
    RegisterRequest:
      $ref: "./schemas/auth.schema.yaml#/RegisterRequest"
    LoginRequest:
      $ref: "./schemas/auth.schema.yaml#/LoginRequest"
    RefreshTokenRequest:
      $ref: "./schemas/auth.schema.yaml#/RefreshTokenRequest"
    AuthResponse:
      $ref: "./schemas/auth.schema.yaml#/AuthResponse"
    UserProfile:
      $ref: "./schemas/auth.schema.yaml#/UserProfile"
    ErrorResponse:
      $ref: "./schemas/auth.schema.yaml#/ErrorResponse"

    # Task Category
    TaskCategory:
      $ref: "./schemas/task.schema.yaml#/TaskCategory"
    TaskCategoryRequest:
      $ref: "./schemas/task.schema.yaml#/TaskCategoryRequest"

    # Task
    Task:
      $ref: "./schemas/task.schema.yaml#/Task"
    TaskRequest:
      $ref: "./schemas/task.schema.yaml#/TaskRequest"
    TaskPatchRequest:
      $ref: "./schemas/task.schema.yaml#/TaskPatchRequest"
    
    # Task Enums
    Timeline:
      $ref: "./schemas/task.schema.yaml#/Timeline"
    Priority:
      $ref: "./schemas/task.schema.yaml#/Priority"
    Status:
      $ref: "./schemas/task.schema.yaml#/Status"
    
    # Shopping Items
    ShoppingItem:
      $ref: "./schemas/shopping.schema.yaml#/ShoppingItem"
    ShoppingItemRequest:
      $ref: "./schemas/shopping.schema.yaml#/ShoppingItemRequest"
    ShoppingItemPatchRequest:
      $ref: "./schemas/shopping.schema.yaml#/ShoppingItemPatchRequest"

    # Shopping Items Enum
    ItemStatus:
      $ref: "./schemas/shopping.schema.yaml#/ItemStatus" 

    # Budget
    Budget:
      $ref: "./schemas/budget.schema.yaml#/Budget" 
    BudgetRequest:
      $ref: "./schemas/budget.schema.yaml#/BudgetRequest" 
      